[package]
name = "workflow"
version = "0.4.1"
edition = "2021"

[dependencies]
templates = {path = "../templates" }
exec = {path = "../exec" }
utils = {path = "../utils" }
cast = {path = "../cast" }
chrono = { version = "0.4.23", features = ["serde"] }
colored = "2.0.0"
log = "0.4.17"
serde = { version = "1.0.152" ,features = ["derive"] }
serde_json = "1.0.93"
uuid = { version = "1.1.2", features = [ "v4","serde","fast-rng","macro-diagnostics"]}
once_cell = "1.16.0"
convert_case = "0.6.0"
rayon = "1.6.1"
miette = { version = "5.5.0" }
thiserror = "1.0.38"
regex = "1.7.1"
strum = { version = "0.24.1", features = ["derive"] }
glob = "0.3.1"
rustix = { version = "0.38.25", features = ["process"] }
serde_plain = "1.0.2"

