[workspace]
resolver = "2"
members = [
  ## Dependencies small utilities crates
  "utils",
  "exec",
  "cast",
  "templates",
  ## Core crates with interdependencies
  "workflow",
  "cli",
  "switch",
  ## Lib entry point
  "pipelight_core",
  ## Bin package
  "pipelight",
]
