[package]
name = "pipelight"
version = "0.1.1"
edition = "2021"

[lib]
name = "lib"
path = "src/lib/lib.rs"

[[bin]]
name = "run"
path = "src/lib/actions/mod.rs"

[dependencies]
clap = { version = "4.0.27", features = ["derive","wrap_help"] }
clap-verbosity-flag = "2.0.0"
json = "0.12.4"
log = "0.4.17"
log4rs = "1.2.0"
project-root = "0.2.2"
serde = "1.0.147"
serde_json = "1.0.89"
subprocess = "0.2.9"
terminal-menu = "2.0.4"
