[workspace]
resolver = "2"
members = [
  ## Dependencies small utilities crates
  "pipelight_utils",
  ## Process management
  "pipelight_exec",
  "cast",
  "templates",
  ## Core crates with interdependencies
  "workflow",
  "cli",
  "switch",
  ## Bin package and Lib entrypoint
  "pipelight",
]
