# Command from:
# https://stackoverflow.com/questions/52176130/how-to-tell-cargo-to-use-git-tags-to-determine-the-crate-version

[[pipelines]]
name = "update_crates version"
[[pipelines.steps]]
name = "gnarly_sed_command"
commands = ["ls"]

[[pipelines]]
name = "test white space"
[[pipelines.steps]]
name = "gnarly_sed_command"
commands = ["ls"]
