[package]
name = "pipelight_exec"
version = "0.2.5"
edition = "2021"
license = "GPL-2.0-only"
description = "Easy process management"

[dependencies]
pipelight_utils = "0.2.5"
git2 = "0.19.0"
rev_buf_reader = "0.3.0"
log = "0.4.22"
log4rs = { version = "1.3.0", features = [
  "json_encoder",
  "pattern_encoder",
  "size_trigger",
  "console_appender",
  "file_appender",
] }
uuid = { version = "1.10.0", features = [
  "v4",
  "serde",
  "fast-rng",
  "macro-diagnostics",
] }
strum = { version = "0.26.3", features = ["derive"] }
serde = { version = "1.0.208", features = ["derive"] }
convert_case = "0.6.0"
once_cell = "1.19.0"
miette = "7.2.0"
serde_plain = "1.0.2"
iso8601-duration = { version = "0.2.0", features = ["serde", "chrono"] }
chrono = { version = "0.4.38", features = ["serde"] }
ignore-files = "3.0.1"
project-origins = "1.4.0"
signal-hook = { version = "0.3.17", features = ["extended-siginfo"] }
console = "0.15.8"
thiserror = "1.0.63"
colored = "2.1.0"
subprocess = "0.2.9"
rustix = { version = "0.38.34", features = ["process"] }
sysinfo = "0.31.2"
itertools = "0.13.0"
serde_json = "1.0.125"
toml = { version = "0.8.19", features = ["parse"] }
hcl-rs = "0.18.0"
serde_yaml = "0.9.34"
