[package]
name = "pipeline"
version = "0.2.0"
edition = "2021"

[dependencies]
exec = {path = "../exec" }
utils = {path = "../utils" }
chrono = "0.4.23"
colored = "2.0.0"
json = "0.12.4"
log = "0.4.17"
rev_buf_reader = "0.3.0"
serde = { version = "1.0.147" ,features = ["derive"] }
serde_json = "1.0.89"
sysinfo = "0.27.0"
uuid = { version = "1.2.2", features = [ "v4","serde","fast-rng","macro-diagnostics"]}
strum = { version = "0.24.1", features = ["derive"] }
strum_macros = "0.24.3"
globals = "1.0.5"
spin = "0.9.4"
global = "0.4.3"
derive_deref = "1.1.1"
once_cell = "1.17.0"
system = "0.1.0"
