[package]
name = "cli"
version = "0.4.0"
edition = "2021"

[dependencies]
workflow = {path = "../workflow" }
templates = {path = "../templates" }
exec = {path = "../exec" }
utils = {path = "../utils" }
cast = {path = "../cast" }
clap = { version = "4.3.1", features = ["derive", "wrap_help", "cargo"] }
chrono = { version = "0.4.23", features = ["serde"] }
colored = "2.0.0"
log = "0.4.17"
serde = { version = "1.0.152" ,features = ["derive"] }
serde_json = "1.0.93"
uuid = { version = "1.1.2", features = [ "v4","serde","fast-rng","macro-diagnostics"]}
once_cell = "1.16.0"
convert_case = "0.6.0"
rayon = "1.6.1"
miette = { version = "5.5.0" }
thiserror = "1.0.38"
regex = "1.7.1"
strum = { version = "0.24.1", features = ["derive"] }
glob = "0.3.1"
rustix = { version = "0.37.20", features = ["process"] }
iso8601-duration = { version = "0.2.0", features = ["serde", "chrono"] }
clap_complete = "4.3.1"
dialoguer = "0.10.3"
sysinfo = "0.28.1"
assert_cmd = "2.0.11"
serde_plain = "1.0.2"
clap_mangen = "0.2.14"

[build-dependencies]
exec = {path = "../exec" }
utils = {path = "../utils" }
chrono = "0.4.23"
clap = { version = "4.3.1", features = ["derive", "wrap_help", "cargo"] }
log = "0.4.17"
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
sysinfo = "0.28.1"
uuid = { version = "1.1.2", features = [ "v4","serde","fast-rng","macro-diagnostics"]}
dialoguer = "0.10.3"
miette = { version = "5.5.0" }
thiserror = "1.0.40"
once_cell = "1.18.0"
rustix = { version = "0.37.20", features = ["process"] }
clap_complete = "4.3.1"
convert_case = "0.6.0"
assert_cmd = "2.0.11"
