[package]
name = "cli"
version = "0.4.0"
edition = "2021"
build = "build.rs"

[dependencies]
workflow = { path = "../workflow" }
templates = { path = "../templates" }
exec = { path = "../exec" }
pipelight_utils = { path = "../utils" }
cast = { path = "../cast" }
chrono = { version = "0.4.23", features = ["serde"] }
colored = "2.0.0"
log = "0.4.17"
once_cell = "1.16.0"
convert_case = "0.6.0"
miette = { version = "5.5.0" }
thiserror = "1.0.38"
glob = "0.3.1"
# clap
clap = { version = "4.3.1", features = ["derive", "wrap_help", "cargo"] }
clap_complete = "4.3.1"
clap_mangen = "0.2.14"
dialoguer = "0.10.3"
assert_cmd = "2.0.11"
# serde
serde = { version = "1.0.152", features = ["derive"] }
serde_plain = "1.0.2"
serde_json = "1.0.93"
# async
tokio = "1.32.0"
rayon = "1.6.1"
watchexec = "2.3.0"
watchexec-events = "1.0.0"
watchexec-signals = "1.0.0"
watchexec-filterer-ignore = "1.2.1"
ignore-files = "1.3.1"

[build-dependencies]
workflow = { path = "../workflow" }
templates = { path = "../templates" }
exec = { path = "../exec" }
pipelight_utils = { path = "../utils" }
cast = { path = "../cast" }
chrono = { version = "0.4.23", features = ["serde"] }
colored = "2.0.0"
log = "0.4.17"
once_cell = "1.16.0"
convert_case = "0.6.0"
miette = { version = "5.5.0" }
thiserror = "1.0.38"
glob = "0.3.1"
# clap
clap = { version = "4.3.1", features = ["derive", "wrap_help", "cargo"] }
clap_complete = "4.3.1"
clap_mangen = "0.2.14"
dialoguer = "0.10.3"
assert_cmd = "2.0.11"
# serde
serde = { version = "1.0.152", features = ["derive"] }
serde_plain = "1.0.2"
serde_json = "1.0.93"
# async
tokio = "1.32.0"
rayon = "1.6.1"
watchexec = "2.3.0"
watchexec-events = "1.0.0"
watchexec-signals = "1.0.0"
watchexec-filterer-ignore = "1.2.1"
ignore-files = "1.3.1"
