[package]
name = "cast"
version = "0.5.8"
edition = "2021"

[dependencies]
exec = { path = "../exec" }
utils = { path = "../utils" }
serde = { version = "1.0.152", features = ["derive"] }
serde_json = "1.0.93"
miette = { version = "5.5.0" }
thiserror = "1.0.38"
serde_yaml = "0.9.19"
log = "0.4.17"
toml = { version = "0.7.3", features = ["parse"] }
