[package]
name = "cast"
version = "0.5.8"
edition = "2021"

[dependencies]
pipelight_utils = { path = "../pipelight_utils" }
serde = { version = "1.0.152", features = ["derive"] }
miette = { version = "5.5.0" }
thiserror = "1.0.38"
log = "0.4.17"
serde_json = "1.0.93"
toml = { version = "0.7.3", features = ["parse"] }
hcl-rs = "0.18.0"
serde_yaml = "0.9.19"
