[package]
name = "pipelight"
version = "0.6.19"
edition = "2021"
authors = ["areskul"]
description = "A Rust/Typescript based absurd automation tool"
homepage = "pipelight.areskul.com"
repository = "git@gitea.com:areska/pipelight.git"
license = "GPL2"

# default-run = "pipelight"

[lib]
name = "pipelight"
path = "src/lib.rs"

[[bin]]
name = "pipelight"
path = "src/bin.rs"

[dependencies]
pipelight_utils = { path = "../utils" }
switch = { path = "../switch" }
log = "0.4.17"
miette = { version = "5.5.0", features = ["fancy", "backtrace"] }
owo-colors = "3.5.0"
