[package]
name = "pipelight"
version = "0.3.0"
edition = "2021"
default-run = "pipelight"
authors = ["areskul"]
description = "A Rust/Typescript based absurd automation tool"
homepage = "pipelight.areskul.com"
repository="git@gitea.com:areska/pipelight.git"
license="GPL2"

[dependencies]
shared = {path = "../shared" }
exec = {path = "../exec" }
pipeline = {path = "../pipeline" }
utils = {path = "../utils" }
log = "0.4.17"
miette = { version = "5.5.0", features = ["fancy"] }

