[package]
name = "pipelight"
version = "0.1.6"
edition = "2021"
default-run = "pipelight"
authors = ["areskul"]
description = "A Rust/Typescript based absurd automation tool"
homepage = "pipelight.areskul.com"
repository="git@gitea.com:areska/pipelight.git"
license="GPL2"

[dependencies]
shared = {path = "../shared" }
log = "0.4.17"
serde_json = "1.0.89"
