[package]
name = "pipelight"
version = "0.6.19"
edition = "2021"
authors = ["areskul"]
description = "A Rust/Typescript based absurd automation tool"
homepage = "pipelight.dev"
repository = "git@github.com:pipelight/pipelight.git"
license = "GPL2"

# default-run = "pipelight"

[lib]
name = "pipelight"
path = "src/lib.rs"

[[bin]]
name = "pipelight"
path = "src/bin.rs"
doc = false

[dependencies]
utils = { path = "../utils" }
switch = { path = "../switch" }
log = "0.4.17"
miette = { version = "5.5.0", features = ["fancy", "backtrace"] }
owo-colors = "3.5.0"
